version: 2.1


orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    docker:
      - image: circleci/android:api-28
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build
  test:
    docker:
      - image: circleci/android:api-28
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew test
    - store_artifacts:
        path: app/build/reports
        destination: reports
workflows:
  version: 2.1
  BuildAndTest:
    jobs:
      - build
      - test