version: 2.1

before_script:
  - touch local.properties

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew build
  test:
    docker:
      - image: circleci/android:api-28-alpha
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew test
