version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          command: ./gradlew build
  test:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          command: ./gradlew test
